/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufo.elkoywoodcutting.main;

import com.ufo.elkoywoodcutting.utils.Location;
import com.ufo.elkoywoodcutting.utils.Trees;
import com.ufo.elkoywoodcutting.utils.Variables;

/**
 * @author UFO
 */
public class Ui extends javax.swing.JFrame {


    /**
     * Creates new form ElkoyWC
     */
    public Ui() {
        setBounds(575, 150, 450, 200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        treeLabel = new javax.swing.JLabel();
        treeComboBox = new javax.swing.JComboBox<>();
        powerLevelCheckBox = new javax.swing.JCheckBox();
        startButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        titleLabel.setText("UFOS WoodCutter");

        treeLabel.setText("Tree:");

        treeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Normal(Lvl 1)", "Oak(Lvl 15)", "Willow(Lvl 30)", "Maple(Lvl 45)", "Yew(Lvl 60)", "Magic(Lvl 75)"}));

        powerLevelCheckBox.setText("Power level");

        startButton.setText("Start script");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(titleLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(powerLevelCheckBox))
                                                        .addComponent(treeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(treeLabel)))
                                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(treeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(powerLevelCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(treeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    public void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        String selected = treeComboBox.getSelectedItem().toString();
        Variables vars = new Variables();

        if (powerLevelCheckBox.isSelected()) {
            vars.setPowerLevel(true);
        }

        if (selected.contains("Normal")) {
            vars.setCity(Location.SEERS_VILL.getCityID());
            vars.setTree(Trees.NORMAL.getTreeID());
        } else if (selected.contains("Oak")) {
            vars.setCity(Location.SEERS_VILL.getCityID());
            vars.setTree(Trees.OAK.getTreeID());
        } else if (selected.contains("Willow")) {
            vars.setCity(Location.DRAYNOR.getCityID());
            vars.setTree(Trees.WILLOW.getTreeID());
        } else if (selected.contains("Maple")) {
            vars.setCity(Location.SEERS_VILL.getCityID());
            vars.setTree(Trees.MAPLE.getTreeID());
        } else if (selected.contains("Yew")) {
            vars.setCity(Location.STRONG_HOLD.getCityID());
            vars.setTree(Trees.YEW.getTreeID());
        } else if (selected.contains("Magic")) {
            vars.setCity(Location.ISAFDAR.getCityID());
            vars.setTree(Trees.MAGIC.getTreeID());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JCheckBox powerLevelCheckBox;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    public static javax.swing.JComboBox<String> treeComboBox;
    private javax.swing.JLabel treeLabel;
    // End of variables declaration
}
